### ISSUE TITLE
Lint script fails for various reasons

### ISSUE THREAD

**Issue by JamesHenry** [eslint/typescript-eslint-parser#10]
We are making progress, slowly but surely, towards getting this repo ready for active development! This issue is to track changes necessary for the project to be able to lint itself successfully.

There are currently a number of reasons why the lint script is failing, including:

- Missing semicolons
- Formatting issues
- Unused code
- Missing JSDoc blocks on existing functions

Obviously some of these things are very easy to remedy without having written any of the code, but others are not. The code which is included, but not used, is particularly difficult to reason about.

I will open a PR and look for your feedback on getting this issue resolved.

Then perhaps we can look at getting the lint script to run as a requisite of future PRs?

**Comment by nzakas** [comment]
Sure! To be honest, I wasn't even going to tackle getting linting to pass until this was further down the road, but you're right that it would be confusing for contributors. So definitely :+1:.

**Comment by JamesHenry** [comment]
Yeah, exactly!

As I mentioned here https://github.com/eslint/typescript-eslint-parser/pull/11#discussion_r50093779, I am trying to approach in the most efficient way possible and go for low-hanging fruit for an "outsider" to the project.

Having the linting working also massively helps future PRs because the code style in this project is quite different to my personal one, for example. This helps nip any possible divergences in code-style in the bud early on.
