### ISSUE TITLE
TypeScript 2.x Support

### ISSUE THREAD

**Issue by JamesHenry** [eslint/typescript-eslint-parser#105]
- [x] Update typescript peerDependency to `^2.0.3` (https://github.com/eslint/typescript-eslint-parser/pull/112)
- Investigate and fix broken tests caused by updated dependency:
  - [x] `jsx/tag-names-with-dots` (https://github.com/eslint/typescript-eslint-parser/pull/108)
  - [x] `jsx/tag-names-with-multi-dots` (https://github.com/eslint/typescript-eslint-parser/pull/108)
  - [x] `basics/declare-namespace-with-exported-function` (https://github.com/eslint/typescript-eslint-parser/pull/107)
  - [x] `decorators/method-decorators/method-decorator-factory-instance-member` (https://github.com/eslint/typescript-eslint-parser/pull/106)
  - [x] `decorators/method-decorators/method-decorator-instance-member` (https://github.com/eslint/typescript-eslint-parser/pull/106)
---
- Transform new constructs introduced in TypeScript 2 (see #90 for additional background)
  - [x] shorthand ambient module declarations (https://github.com/eslint/typescript-eslint-parser/pull/109)
  - [x] non-null assertion operator (https://github.com/eslint/typescript-eslint-parser/pull/110)
  - [x] typed usages of `this` (https://github.com/eslint/typescript-eslint-parser/pull/112)

---
- [x] Add parameter type annotations to the AST (requisite for typed-this) (https://github.com/eslint/typescript-eslint-parser/pull/111)

**Comment by JamesHenry** [comment]
Update:

The `decorators/method-decorators/method-decorator-factory-instance-member` and `decorators/method-decorators/method-decorator-instance-member` tests fail because I just so happen to have call my made up decorator `readonly`, which became a keyword in TypeScript 2.

**Comment by JamesHenry** [comment]
The `basics/declare-namespace-with-exported-function` test fails because a particular `flags` value on the `deeplyCopy()`ed TSNode has changed between TS 1.x and TS 2.x

Whilst we do use TSNode.flags for some node checks, there is not actually any reason to pass them through to the converted AST when using the `deeplyCopy()` fallback. It does not provide and current benefit, and we will always be exposed to these kinds of changes.

Therefore the change I will make is to exclude flags from the copy process, rather than changing the value in the final AST.

**Comment by JamesHenry** [comment]
`jsx/tag-names-with-dots` and `jsx/tag-names-with-multi-dots` were pretty tricky to track down and fix.

The change is AST between TS 1.8.10 and TS 2.0.3 can be attributed to this PR https://github.com/Microsoft/TypeScript/pull/7645

**Comment by dannyfritz** [comment]
Dang that was quick. ✨

**Comment by corbinu** [comment]
Nice work! as soon is up will run it through my Smoke Testing (obviously most will fail still) but hopefully when Eslint 4 drops we will be 100%!

**Comment by corbinu** [comment]
@JamesHenry Ran the smoke tests. No new failures.

https://gitlab.com/corbinu/eslint-typescript-smoketest/pipelines/4930979

All the failures are still in escope (as expected) except for the nativescript groceries sample which is failing on no-unused-vars and no-undef which is not un expected either.

https://gitlab.com/corbinu/eslint-typescript-smoketest/builds/6041509

**Comment by JamesHenry** [comment]
Cool, thanks @corbinu! Now that TS 2 support is in, I'll be looking at the escope stuff
