### ISSUE TITLE
Parser does not handle jsdoc well

### ISSUE THREAD

**Issue by jtheoof** [eslint/typescript-eslint-parser#118]
**What version of TypeScript are you using?**
2.1.1

**What version of `typescript-eslint-parser` are you using?**
1.0.0

**What code were you trying to parse?**

```
/**
 * This crashes eslint.
 */
export interface Test {
    name: string;
}
```

**What did you expect to happen?**
Syntax should parse correctly

**What happened?**
Stacktrace:

```
Cannot read property 'loc' of undefined
TypeError: Cannot read property 'loc' of undefined
    at getNodeIndent (/Users/jattali/dev/mnubo/mnubo-front-end/app/node_modules/eslint/lib/rules/indent.js:236:54)
    at EventEmitter.Program (/Users/jattali/dev/mnubo/mnubo-front-end/app/node_modules/eslint/lib/rules/indent.js:793:49)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/Users/jattali/dev/mnubo/mnubo-front-end/app/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/jattali/dev/mnubo/mnubo-front-end/app/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/Users/jattali/dev/mnubo/mnubo-front-end/app/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/Users/jattali/dev/mnubo/mnubo-front-end/app/node_modules/eslint/lib/eslint.js:903:36)
    at Controller.__execute (/Users/jattali/dev/mnubo/mnubo-front-end/app/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/jattali/dev/mnubo/mnubo-front-end/app/node_modules/estraverse/estraverse.js:501:28)
```

Note: If you remove the `jsdoc` comments, `eslint` does not crash anymore.

**Comment by jtheoof** [comment]
In fact, if you replace:

```
/**
 * This crashes eslint.
 */
```

with:

```
/*
 * This crashes eslint.
 */
```

`eslint` is happy again.

**Comment by jtheoof** [comment]
Probably related to #5

**Comment by weirdpattern** [comment]
@nzakas if you don't mind, I think I may have a fix for this and a way to attributing all comment nodes (single line, multiline and jsdoc) as mentioned by @JamesHenry in #5. I think this will enable rules like valid-jsdoc and others... 

Code is done, but I'm still working on the tests, so give me a couple of days and I will send a PR.

**Comment by JamesHenry** [comment]
Thanks for the suggestion, @weirdpattern!

You must have missed the resolution in that issue https://github.com/eslint/typescript-eslint-parser/issues/5#issuecomment-245720268 - comment attribution will be done in an upcoming version of ESLint, not in this project, nor any other other future parsers.

**Comment by weirdpattern** [comment]
@JamesHenry But we still need to identify the comments and convert them to estree nodes, right? Maybe I misunderstood the whole thing, the code I'm working on does that, identify and convert comments in typescript, let me know if this is still something we don't need and I will just move on to a different issue =)

**Comment by nzakas** [comment]
Yes, comments will still need to be converted and included in the top level comments array, so I think we still need this fixed.

**Comment by weirdpattern** [comment]
ok, then give me a couple of days to complete the unit tests, then I will submit a PR for you to review...

**Comment by JamesHenry** [comment]
@weirdpattern The logic to scan for and convert comments was already added here https://github.com/eslint/typescript-eslint-parser/blob/41ccef5228f2b7574992e97dce78f1aa1b2dfaee/parser.js#L184-L212, but some active assertions will definitely be needed.

We currently have old espree test fixtures within attach-comments, but I think it might be best to wait until the comment attribution support lands in ESLint 4, before attempting to finalise how and what we test in this parser.

Many thanks for your offer to contribute, it is always welcome!

**Comment by weirdpattern** [comment]
Makes sense, let's wait for eslint 4 to be released, then we can discuss.

thanks for taking the time to answer my questions =)

**Comment by JamesHenry** [comment]
This is not actually a bug in the currently supported logic (TypeScript 2.0.x).

This is an issue that applies to supporting 2.1.x, which is now being worked on in https://github.com/eslint/typescript-eslint-parser/issues/128

Closing this issue in favour of that one, particularly to avoid the confusion with comment attribution, which is a totally separate issue.
