### ISSUE TITLE
Namespace exported function return causing later code to be marked unreachable

### ISSUE THREAD

**Issue by blemoine** [eslint/typescript-eslint-parser#127]
**What version of TypeScript are you using?**
TypeScript 2.1.4

**What version of `typescript-eslint-parser` are you using?**
typescript-eslint-parser@1.0.0
 eslint@3.12.1

**What code were you trying to parse?**

```
export namespace query {
    export interface Query {
        from: string;
    }

    export function isQuery(query: any): query is Query {
        return (query as Query).from !== undefined;
    }
}

export type SearchQuery = query.Query;
```

**What did you expect to happen?**

With 

```
"rules": {
      'no-unreachable': 2
    }
```

 in my config, I would expect no error (the last line is reachable, because it's exported)

**What happened?**

I get "Unreachable code  no-unreachable" error.
When I remove the type guard function, the problem disappear.

**Comment by blemoine** [comment]
I provide more information here : 
 - the code above is a in file test.ts
 - my full config is : 
    ```
   {
       "parser": "typescript-eslint-parser",
       "rules": {
          "no-unreachable": 2
       }
    }
   ``` 

And the full output from eslint is: 

```
/Users/******/tslint-bug/test.ts
  11:5  error  Unreachable code  no-unreachable

✖ 1 problem (1 error, 0 warnings)
```

Do you need any other informations?

**Comment by JamesHenry** [comment]
I can reproduce the issue with your example, thanks @blemoine. I will look into this!

**Comment by JamesHenry** [comment]
The type guard is actually not relevant... It is the return statement inside an exported function from the namespace that is the key.

Here is the minimal example for reproducing the issue:
```
export namespace foo {
    export function bar() {
        return;
    }
}
export type Qux = true;
```

`export type Qux = true;` will currently be flagged as unreachable.

**Comment by soda0289** [comment]
Here is another example:
```typescript
/* eslint-disable no-undef */
namespace foo {

   function bar() {
        return;
   }

   //Unreachable code.
   function baz() {
        return;
   }
}
```

I think the problem is that the code analyzer is not creating a new code path when the function ends. Will look into this more tonight, might need to patch eslint or create a new rule in the plugin.

**Comment by soda0289** [comment]
I spent some more time on this.
The issue is that functions inside namespaces are given node type: TSNamespaceFunctionDeclaration instead of standard FunctionDeclaration.
https://github.com/eslint/typescript-eslint-parser/blob/master/lib/ast-converter.js#L882-L887

Not sure why this is the case but if you keep the functions type to FunctionDeclartion the rule works as expected.

**Comment by soda0289** [comment]
Looks like it was to fix a bug with empty body function in namespaces:
PR: https://github.com/eslint/typescript-eslint-parser/pull/82
Issue: https://github.com/eslint/typescript-eslint-parser/issues/78

Maybe we can have it so if the there is a body to the function we keep the type to FunctionDeclaration. 

What are your thoughts @JamesHenry

**Comment by mightyiam** [comment]
Makes sense to me that a function declaration remains of node type `FunctionDeclaration` regardless of the context in which it is in.
