### ISSUE TITLE
Make compatible with TypeScript 2.1

### ISSUE THREAD

**Issue by flying-sheep** [eslint/typescript-eslint-parser#128]
When installing TypeScript 2.1, tests start to fail. This is why travis is currently failing for every PR.

We should handle the AST it produces.

**Comment by soda0289** [comment]
I will take a look at some of these tests.

**Comment by JamesHenry** [comment]
I'm looking into this now. I will be putting together a list of updates needed on this issue.

- [ ] exclude new `modifierFlagsCache` property during TSNode auto-conversion

**Comment by JamesHenry** [comment]
Just FYI, I have asked for some feedback from the TypeScript on the final point, as I would love to get this over the line:

https://github.com/Microsoft/TypeScript/issues/13519

**Comment by JamesHenry** [comment]
This has been confirmed as a TypeScript bug, so unfortunately the upgrade to 2.1.x is blocked for now

**Comment by jtheoof** [comment]
Thanks for the feedback @JamesHenry.

**Comment by JamesHenry** [comment]
I have a final update on this, but this issue has gotten rather messy, and it was not my original description, so I am going to start a new one which just summarises how ts-2.1 support works for this parser.

The instructions are here: https://github.com/eslint/typescript-eslint-parser/issues/149
