### ISSUE TITLE
Development Plan

### ISSUE THREAD

**Issue by nzakas** [eslint/typescript-eslint-parser#13]
- [x] Phase 1: Full ES6 support, stripping out all TypeScript-specific syntax.
- [x] Phase 2: Add JSX support.
- [x] Phase 3: Add support for attaching comments.
- [x] Phase 4: Add support for type annotations (try to mimic [what Flow uses](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/estree/flow.d.ts) and use the [type annotations extension](https://github.com/estree/estree/pull/122) to ESTree).
- [x] Phase 5: Add support for TypeScript-specific syntax (interfaces, etc.). Once again, I'd like to mimic what Flow does as much as possible (with the exception of use "TS" rather than "Flow") where there are commonalities.

**Comment by nzakas** [comment]
I think phase 1 might actually be complete, but need to double-check.

**Comment by JamesHenry** [comment]
Yes it is definitely starting to come together!

I was able to submit a fix for the known issue #1, and retried running it on my large TypeScript + Angular 1.x app again.

Seems like ParameterDecorators are causing `Parsing error: Unexpected token` right now. I have submitted an issue for that here: https://github.com/eslint/typescript-eslint-parser/issues/19

I make heavier use of them, so the output is very noisy right now, but I will look into a fix and submit any further issues I come across.

**Comment by Gheoan** [comment]
Where do typescript only features fit in this plan (ex: [class members accessibility](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#822-accessibility))?

**Comment by nzakas** [comment]
@Gheoan Phase 5. That's where we tackle all the other syntax not already addressed.

**Comment by dtaub** [comment]
The order here does not match what is in the README; should the README be updated?

**Comment by nzakas** [comment]
Yes

**Comment by nzakas** [comment]
I think we are done here. Now just working on bugs.
