### ISSUE TITLE
Async function makes all variables constant

### ISSUE THREAD

**Issue by NeoReyad** [eslint/typescript-eslint-parser#136]
**What version of TypeScript are you using?**
2.1.4

**What version of `typescript-eslint-parser` are you using?**
1.0.1

**What code were you trying to parse?**

```
async function test() {
     var foo = null;
     foo = 'hhh';
}

```

**What did you expect to happen?**
I excepted no errors.

**What happened?**
Eslint error 'foo is constant (no-const-assign)'

**Comment by NeoReyad** [comment]
@flying-sheep Any ideas?

**Comment by NeoReyad** [comment]
I'm using the ts-2.1 branch rebased on master.

**Comment by flying-sheep** [comment]
i’m confused: why was i subscribed to this? i don’t see an @-mention…

was there one that you removed?

**Comment by NeoReyad** [comment]
Yes sorry my fault. I mentioned you in a comment but later realized that this bug is most likely caused by typescript 2.1 and not your patch. I deleted the comment as I'm still looking into the issue. Sorry about the noise.

**Comment by flying-sheep** [comment]
no problem 😄

**Comment by NeoReyad** [comment]
I have tested this with Typescript Version 2.0.3 and typescript-eslint-parser 1.0.1 and have run into the same problem. I believe it is because the code uses and equal comparison on bit-wise flags which becomes false when an async flag is added. We could change it to an and(&) comparison or use the utilities function like I have done in pull request (#137). I will create another pull request against master when I get some free time.
