### ISSUE TITLE
Student project

### ISSUE THREAD

**Issue by DatenMetzgerX** [eslint/typescript-eslint-parser#14]
Hy everyone

I started with my master degree and we are obligated to write at least two project thesis (and at last the master thesis). I want to focus my project thesis on improving the developer tools for javascript and compile to javascript languages. My first idea was to implement more complex linting rules for javascript, but eslint already supports the most of the rules I came up with. At the other hand I think that type information would allow to implement more complex linting rules. 

I have worked for 10 years in various, large, web based, enterprise projects with a focus on javascript for the last 4 years. My last projects have used Typescript, so I'm familiar with the concepts of Typescript (at least up to version 1.7). I have no experience with ESLint as we have used JSHint in our projects. 

Personally I'm more interested in flow, but I see that Typescript has the larger community and it's importance will increase in the near future. But at the end I think it's not that important if it is Typescript or Flow that is supported in a first case. 

Are you interested in any form of contribution? Are there active contributors? Is someone responsible for the project or is it abandoned? (I don't want to implement something that someone else will implement in the same time, so I think some coordination is required).  I'm interested in the benefits you are expecting from adding the type information to ESLint or what your goals are for this project. Have you already some additional rules in mind that require the additional type information or should it be an alternative to TSLint?

Cheers,
Micha

**Comment by BYK** [comment]
Hi @DatenMetzgerX - glad to hear you are interested. The project is most definitely not abandoned and we are looking for contributors/help. You can see https://github.com/eslint/typescript-eslint-parser#contributing and referenced document to how to get started. We also have a gitter.im chat room (eslint/eslint) if you want to come by and a mailing list.

**Comment by JamesHenry** [comment]
Hey guys,

Just wanted to provide some extra context in addition to what @BYK mentioned...

ESLint 2.x has been a massive effort, and as such has been the primary focus of core contributors to the project. Now that it is out the door, I am hopeful that we can really get the ball rolling with this project (as a regular TS user myself).

I have been working hard to contribute to this repo wherever possible, but it has been a bit of a challenge so far. I got the chance to chat with @nzakas about it, and the biggest problem right now is that the tests do not work (never mind pass).

@nzakas has said he will work on fixing that when he gets chance and that will unlock the potential of further contributions by @DatenMetzgerX and others.

- More info on the broken tests: https://github.com/eslint/typescript-eslint-parser/issues/6
- Development plan for this project: https://github.com/eslint/typescript-eslint-parser/issues/13

Cheers,

James

**Comment by nzakas** [comment]
Yeah, sorry, between ESLint 2.0.0 and some health problems, I've not been able to get back around to this. It's still on my list, hopefully soon!

**Comment by nzakas** [comment]
The outstanding issues with testing have been completed, so it's a good time to start with other contributions.

> Have you already some additional rules in mind that require the additional type information or should it be an alternative to TSLint?

Not right now. The goal is first to get this parser ready for use, and then investigate what sort of changes (if any) might be made to the ESLint core. I think the logical next step after making this parser work is to create a TypeScript plugin with TypeScript-specific rules.

**Comment by DatenMetzgerX** [comment]
Hy everyone

Thanks a lot for the update. We (Myself and my supervisor) decided to focus the work on plain javascript. Working on this project was no option for my supervisor as it is unclear what my contribution would be and what has been contributed by others. 

But I'm still quite interested in the project and will follow the progress you made. I wish you good luck and maybe our ways cross again when I need to choose another project topic. 

Cheers, Micha
