### ISSUE TITLE
[Error] Global Node Objects '__dirname' and '__filename'

### ISSUE THREAD

**Issue by ajtorres9** [eslint/typescript-eslint-parser#145]
**What version of TypeScript are you using?**
2.0.3

**What version of `typescript-eslint-parser` are you using?**
1.0.2

**What code were you trying to parse?**

```
export const sequelizeData = new Umzug({

  migrations: {
    params: [sequelize.getQueryInterface(), Sequelize],
    path: path.resolve(__dirname, './seeders'),
    pattern: /^[A-Z]+\.js$/i,
  },

  storage: 'sequelize',

  storageOptions: {
    modelName: 'SequelizeData',
    sequelize,
    tableName: 'sequelize_data',
  },

});
```

**What did you expect to happen?**
This project was originally pure JavaScript, my team and I are currently in the process of migrating it to TypeScript. Prior to the migration, the line: ```path: path.resolve(__dirname, './seeders'),```, would pass our linting rules.

**What happened?**
After implementing 'typescript-eslint-parser', the line: ```path: path.resolve(__dirname, './seeders'),```, results in a 'no-undef' error.

**Comment by nzakas** [comment]
Can you please paste in the complete error you're seeing?

**Comment by ajtorres9** [comment]
No problem. The following image is the error produced by ESLint:

![no-undef](https://cloud.githubusercontent.com/assets/450495/22221051/2af178a4-e166-11e6-904f-19692453a7dd.png)

I am not sure if this has any relevance at all, but it looks like '__dirname' in the image has 3 underscores preceding the word "dirname" as opposed to the expected 2.

**Comment by soda0289** [comment]
This looks to be a bug in typescript. Any variable, function, or class declaration that starts with two underscores will have three when parsed.

Related:
https://github.com/Microsoft/TypeScript/issues/11902
https://github.com/Microsoft/TypeScript/issues/3268

Will look into a possible fix.

**Comment by soda0289** [comment]
I have opened a new typescript issue for this bug:
https://github.com/Microsoft/TypeScript/issues/14013

**Comment by JamesHenry** [comment]
Thanks for hunting that down, @soda0289! I'll ping the TypeScript team if they don't pick up on that issue soon

**Comment by soda0289** [comment]
Got a response from typescript. We can use the [unescapeIdentifier](https://github.com/Microsoft/TypeScript/blob/d24b6891d870dbaa6bbc358ab787da935f471186/src/compiler/utilities.ts#L402-L404) function to return the real identifier name. Will submit PR soon.

**Comment by JamesHenry** [comment]
@ajtorres9 This should now be fixed on master. NPM update will likely follow once the other open PR is merged

**Comment by ajtorres9** [comment]
Thanks all for your efforts, I appreciate it. 👍
