### ISSUE TITLE
Parameters with assignations do not provide type annotation information

### ISSUE THREAD

**Issue by weirdpattern** [eslint/typescript-eslint-parser#146]
What version of TypeScript are you using?
2.0.3 and 2.1.5

What version of typescript-eslint-parser are you using?
1.0.2

What code were you trying to parse?
```ts
function message(name: string= "foo"): string {
    return name;
}
```

What did you expect to happen?
Parameters with assignation must also provide type annotation information.

What happened?
Parameters with assignation are not providing type annotation information.

**Comment by nzakas** [comment]
> Parameters with assignation are not providing type annotation information.

What does this mean, exactly? Are you saying the type annotation is missing from the AST?

**Comment by weirdpattern** [comment]
Yes sir, the "typeAnnotation" node is missing.
I assumed the node should be part of the "left" node in the "AssignmentPattern"
