### ISSUE TITLE
How to enable TypeScript 2.1.x Support

### ISSUE THREAD

**Issue by JamesHenry** [eslint/typescript-eslint-parser#149]
This issue was originally tracked here: https://github.com/eslint/typescript-eslint-parser/issues/128, but it has now come to its final resolution.

Unfortunately, there was an unintentional breaking change in TypeScript around how it deals with JSDoc comments within some of its public node utility methods that we rely on in this parser.

TS Issue: https://github.com/Microsoft/TypeScript/issues/13519

That issue has now been fixed, but will not be released as a patch version of TypeScript 2.1.x

**This means that it is not possible to _officially_ support TS 2.1.x in this parser**. We will, of course, work to support 2.2.x as soon as possible.

However, because the necessary changes on our side were actually already made, it is still possible for you to use TypeScript 2.1.x on your project.

You can:
- Install this parser using git: the branch name is `ts-2.1`
- Use `typescript@next` as your TypeScript version (this is the master branch of TypeScript, which contains the fix)

(I _think_ this requires npm 3+ (i.e. Node 6+) because otherwise, the peerDependency conflict would prevent you from installing that combo)

**Comment by NeoReyad** [comment]
@JamesHenry could you rebase ts-2.1

**Comment by JamesHenry** [comment]
@NeoReyad Done!

**Comment by JamesHenry** [comment]
Rebased the `ts-2.1` branch again just now after the PR merges earlier today. I will be looking into TS 2.2.x support this week, given that it has now hit release candidate.

**Comment by JamesHenry** [comment]
I'm delighted to say that the first RC of 2.2 passes all of our existing test cases on this `ts-2.1` branch, so hopefully supporting TypeScript 2.2 will be much more straightforward than 2.1.

We will look to update master as soon at 2.2 is the stable release of TypeScript

**Comment by soda0289** [comment]
@JamesHenry Typescript 2.2 is released! Could we merge in this fix.
