### ISSUE TITLE
ParameterDecorators throwing parse errors

### ISSUE THREAD

**Issue by JamesHenry** [eslint/typescript-eslint-parser#19]
#### Environment:
**eslint**: `2.2.0`
**typescript-eslint-parser**: `master` (npm publish is needed to update the project)

---

#### Issue:
Currently when parsing a file which contains a `ParameterDecorator` eslint will return `Parsing error: Unexpected token`. This is not the case for ClassDecorators.

---

#### Background to my use case:

ParameterDecorators are super useful in an Angular world for dependency injection annotations.

Angular has long since used function parameters as a way to supply dependencies to services, controllers, components etc.

The name of the parameter is important, as the injector uses it to look up the value of the dependency that was registered against it, therefore to ensure that it survives minification you can add a static $inject array to the function/class and specify the names of the dependencies as strings.

E.g. pre-TypeScript:
```
function MyService( MyDependency ) {
  console.log(MyDependency)
}
MyService.$inject = ['MyDependency']
```

Using a ParameterDecorator with TypeScript, we can built that static $inject array dynamically based on the value passed in to the decorator:

```
function Inject( injectableName: string ): ParameterDecorator {
	return function parameterDecorator( target: Object, propertyKey: string, parameterIndex: number ) {
		// if propertyKey is set we are injecting into static method not to constructor
		const injectionTarget: any = propertyKey ? target[ propertyKey ] : target
		injectionTarget.$inject = injectionTarget.$inject || []
		injectionTarget.$inject[ parameterIndex ] = injectableName
	}
}

class MyService {
	constructor(@Inject('MyDependency') MyDependency) {
		console.log(MyDependency)
	}
}
console.log(MyClass.$inject) // ['MyDependency']
```

Angular 2 will also make heavy use of ParameterDecorators for its dependency injection out of the box.

**Comment by JamesHenry** [comment]
I noticed that TypeScript is the parser that seems to be able to generate an AST for this:
http://astexplorer.net/#/UIZKxfXxum

Does that suggest that espree itself will need an update? Or does it just require a bit more work to remove the ParameterDecorator syntax when parsing in typescript-eslint-parser?

**Comment by nzakas** [comment]
> Does that suggest that espree itself will need an update?

This is invalid JavaScript syntax, so Espree is doing the right thing. 

> Or does it just require a bit more work to remove the ParameterDecorator syntax when parsing in typescript-eslint-parser?

Probably this. I wasn't aware of this syntax when I did my first pass, so it's probably incorrectly transforming that parameter.

**Comment by valorkin** [comment]
may be relative to this, may be not
this use case failing too:
```
class Test {
  @HostBinding('class.panel-open')
  @Input()
  public get isOpen():boolean {
    return true;
  }
}
```
working on it

**Comment by JamesHenry** [comment]
I wanted to readdress this, but the great news is that when parsing my codebase with `typescript-eslint-parser: 0.1.1` and `eslint: 3.2.2` this is no longer an issue
