### ISSUE TITLE
Cannot find module 'acorn-jsx/inject' - dependency missing

### ISSUE THREAD

**Issue by JamesHenry** [eslint/typescript-eslint-parser#2]
(Note: I am using ESLint via eslint-loader for webpack)
ESLint: 1.9.0
eslint-loader: 1.1.1
typescript-eslint-parser: 0.1.0-alpha-1

`acornJSX = require("acorn-jsx/inject")` is part of the var declaration at the top of parser.js but acorn-jsx is not a dependency of the project.

It doesn't seem like `acornJSX` is actually used anywhere, would you like a PR with the require statement removed?

**Comment by nzakas** [comment]
Whoops, yeah. That should be removed.
