### ISSUE TITLE
Cannot read property 'type' of null at EventEmitter.JSXOpeningElement

### ISSUE THREAD

**Issue by mattdell** [eslint/typescript-eslint-parser#210]
**What version of TypeScript are you using?**
2.2.1

**What version of `typescript-eslint-parser` are you using?**
2.0.0

**What code were you trying to parse?**

```
import React from "react";

interface CounterProps {
  counter: number;
}

export default (props: CounterProps) => (
  <div style={{ margin: "0 auto" }} >
    <h2>Counter: {props.counter}</h2>
  </div>
);
```

**What did you expect to happen?**
Parse all the things!

**What happened?**
`Cannot read property 'type' of null at EventEmitter.JSXOpeningElement ...`

This seems to parse fine without the `<h2>` block.

**Comment by soda0289** [comment]
Could you try the master branch. There is a JSX fix in there that has not been released yet and might fix the problem.

Are you using eslint-plugin-react or is this just with eslint core rules? I think some rules do not work properly in that plugin. Also could you post the full stack trace if possible.

**Comment by mattdell** [comment]
Thanks for the speedy response. I'll try this master branch shortly.

Couldn't post the full stack because of having to use two computers. Will get a full stack for you asap.

**Comment by mattdell** [comment]
I've put my package.json to the last commit in the master branch, like so...

```json
{
    "typescript-eslint-parser": "git+https://github.com/eslint/typescript-eslint-parser.git#1e73711",
}
```

... but that still gives an error. I get the same (different) error now even if I use 2.0.0. The only difference is the initial error is on a PC and the below is on a Mac. 🤔

The full stack is
```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at EventEmitter.Literal (/Users/mdell/Repos/my-project/web/node_modules/eslint/lib/rules/no-empty-character-class.js:49:26)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/Users/mdell/Repos/my-project/web/node_modules/eslint/lib/util/node-event-generator.js:39:22)
    at CodePathAnalyzer.enterNode (/Users/mdell/Repos/my-project/web/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Users/mdell/Repos/my-project/web/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.enter (/Users/mdell/Repos/my-project/web/node_modules/eslint/lib/eslint.js:928:36)
    at Controller.__execute (/Users/mdell/Repos/my-project/web/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/mdell/Repos/my-project/web/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/Users/mdell/Repos/my-project/web/node_modules/eslint/lib/util/traverser.js:36:33)
```

**Comment by soda0289** [comment]
This sounds similar to this issue:
https://github.com/eslint/typescript-eslint-parser/issues/172

You need to make sure that typescript 2.21 or 2.2.2 is installed since previous versions had a bug when traversing JSX tokens. 

If you are running eslint from the command line it will use the globally installed version of typescript-eslint-parser, not the one installed via package.json. It will also used the globally installed typescript package.

You should be able to run this command to check which version of typescript is installed globally with typescript-eslint-parser:
`npm ls typescript -g`

**Comment by mattdell** [comment]
Thanks for the tip. I didn't know about it using the global typescript version on the command line. #172 gave me the idea to update eslint to latest, along with all associated plugins and config.

That has resulted in a minor success... 

```
/Users/mdell/Repos/my-project/web/src/components/Counter/Counter.tsx
   9:158  error  HTML entities must be escaped  react/no-unescaped-entities
   9:178  error  HTML entities must be escaped  react/no-unescaped-entities
   9:182  error  HTML entities must be escaped  react/no-unescaped-entities
   9:183  error  HTML entities must be escaped  react/no-unescaped-entities
   9:187  error  HTML entities must be escaped  react/no-unescaped-entities
  10:198  error  HTML entities must be escaped  react/no-unescaped-entities
```

Have you seen this one before?

**Comment by soda0289** [comment]
Yes unfortunately there are a couple of rules in react plugin that do not work:
```
no-unsecaped-entites
self-closing-comp
void-dom-elements-no-children
jsx-indent
jsx-indent-props
jsx-max-props-per-line
```

There could be more and some might work in your code base. 

I think most of the issues have to do with the way typescript finds the next JSX token which is causing errors or sometimes infinite loops. Will need to spend more time looking into.

**Comment by mattdell** [comment]
That's good to know. I should just be able to disable those rules (for now) and then happy days?

```
  react/no-unsecaped-entites: 0
  react/self-closing-comp: 0
  react/void-dom-elements-no-children: 0
  react/jsx-indent: 0
  react/jsx-indent-props: 0
  react/jsx-max-props-per-line: 0
```

Doesn't seem to rid the issue. 🤔

**Comment by soda0289** [comment]
Sorry, I had a typo in my original answer:
`react/no-unsecaped-entites` should be `react/no-unsecaped-entities`

**Comment by mattdell** [comment]
Actually one more typo... it's `react/no-unescaped-entities`.

More importantly, it works! 🎉 🎉 🎉 

Any idea when you'll be pushing master to npm?

**Comment by soda0289** [comment]
I'm sorry I suck at typing 😄

I will open a new issue with a list of known issues for react-plugin. I'm glad you got it working!

**Comment by soda0289** [comment]
I will try to push a new version today.

**Comment by soda0289** [comment]
@mattdell typescript-eslint-parser 2.1 has been released. I will open a new issue about react plugin issues
