### ISSUE TITLE
Upgrade to ES6 and drop support for Node version < 4

### ISSUE THREAD

**Issue by soda0289** [eslint/typescript-eslint-parser#220]
Currently this parser still supports Node version 0.10 and uses ESLint v2 for linting. We should upgrade the codebase to ES6, using const and let, and stop using the assign library when the native `Object.assign()` can be used instead.

**Comment by JamesHenry** [comment]
I'm working on this as part of my work today, because more and more changes are becoming more difficult as a result of our current setup
