### ISSUE TITLE
TS peer dependency causing build to fail

### ISSUE THREAD

**Issue by JamesHenry** [eslint/typescript-eslint-parser#231]

**Comment by azz** [comment]
Are there many TS2.3 AST changes from TS2.2? 

Looks like the breaking changes docs aren't updated:
https://github.com/Microsoft/TypeScript-wiki/blob/master/API-Breaking-Changes.md

**Comment by JamesHenry** [comment]
> Are there many TS2.3 AST changes from TS2.2?

I don't know, please note anything you find on here: https://github.com/eslint/typescript-eslint-parser/issues/232

The AST does not form part of the API surface that is publicly supported, so the changes are never _directly_ in that document you referenced.

**Comment by Telokis** [comment]
@JamesHenry How could I get rid of `npm WARN typescript-eslint-parser@2.1.0 requires a peer of typescript@~2.2.1 but none was installed.`, please?
I have

```
"typescript": "^2.3.2",
"typescript-eslint-parser": "^2.1.0",
```

inside my devDependencies. But it keeps showing.

**Comment by soda0289** [comment]
Currently only the master branch supports typescript 2.3. Will try and get a new release out this week.

**Comment by Telokis** [comment]
Oh, I thought `2.1.0` was the master version, that's why I got confused.
Thanks for the (**very**) quick answer!

**Comment by JamesHenry** [comment]
@Telokis You would need to install `typescript-eslint-parser` from github for now.

We have been merging in a lot of breaking changes recently which has delayed an official npm release. Sorry for the delay on that, but in the meantime, you can either live with the warning, or install from github.

**Comment by Telokis** [comment]
Guess I'll live with it, then!
