### ISSUE TITLE
Support TypeScript 2.3

### ISSUE THREAD

**Issue by JamesHenry** [eslint/typescript-eslint-parser#232]
TypeScript 2.3 was recently released as the latest stable version and we should look to support it as soon as possible.

On initial inspection of a broken build, it looks like JSX will be the main area of focus for changes.

**Comment by soda0289** [comment]
We will also need to support async iterators as well. I think we can just use a flag on the for loop node.

**Comment by soda0289** [comment]
I can look into the JSX issues unless @azz is already working on it.

**Comment by inuscript** [comment]
Is this fix is released? (or When is this fix published?)

**Comment by soda0289** [comment]
@inuscript We have typescript support in the master branch. We are currently working towards releasing a new major version, v3. Not sure exactly on time frame of new release but should be fairly soon.
