### ISSUE TITLE
Line comments strip /**/

### ISSUE THREAD

**Issue by azz** [eslint/typescript-eslint-parser#256]
**What version of TypeScript are you using?**

2.3.2

**What version of `typescript-eslint-parser` are you using?**

a294afa8158c9c088521eed72b6745eed302361c

**What code were you trying to parse?**

```
// /*test*/
```

**What did you expect to happen?**

```
comments: [ { type: 'Line', value: ' /*test*/', ...} ]
```

**What happened?**

```
comments: [ { type: 'Line', value: ' test', ... } ]
```

prettier/prettier#1480

**Comment by soda0289** [comment]
When parsing comments we currently strip out all comment indicators:
https://github.com/eslint/typescript-eslint-parser/blob/master/parser.js#L226

I will have to look into why this is the case. I think it might be better to just strip the `//` from the begging of a line comment. And strip `/*` and `*/` from a multiline comment but keeping all other characters.

**Comment by soda0289** [comment]
I'm going to fix this in: https://github.com/eslint/typescript-eslint-parser/pull/219
