### ISSUE TITLE
Publish latest master to npm for TS 2.3 support

### ISSUE THREAD

**Issue by maxhoffmann** [eslint/typescript-eslint-parser#273]
**What version of TypeScript are you using?**
`2.3.2`

**What version of `typescript-eslint-parser` are you using?**
`2.1.0`

**What code were you trying to parse?**
Iterating over a ES2015 Set/Map using the `-downlevelIteration` flag.

**What did you expect to happen?**
That `typescript-eslint-parser` supports TS 2.3.

**What happened?**
I can’t use TS 2.3 because `typescript-eslint-parser` lists TS 2.2 as a peer dependency.

**Comment by soda0289** [comment]
Will look into doing one in next couple days. There are some bug fix PRs that need to be reviewed and merged.

You can use the master branch for now as it should be stable.

**Comment by maxhoffmann** [comment]
Thanks for the quick response! Looking forward to it.
