### ISSUE TITLE
RegExp triggers false positive no-magic-numbers

### ISSUE THREAD

**Issue by mdebruijne** [eslint/typescript-eslint-parser#287]
**What version of TypeScript are you using?**
2.3.3

**What version of `typescript-eslint-parser` are you using?**
3.0.0

**What code were you trying to parse?**
echo "console.log(typeof /[a-z]/)" | eslint --stdin --no-eslintrc --parser typescript-eslint-parser --rule '"no-magic-numbers": ["error"]'

**What did you expect to happen?**
Same result as with default parser; echo "console.log(typeof /[a-z]/)" | eslint --stdin --no-eslintrc --rule '"no-magic-numbers": ["error"]'

no errors, exitcode 0

**What happened?**
1:20  error  No magic number: /[a-z]/  no-magic-numbers
1 problem (1 error, 0 warnings)

exitcode 1

**Comment by soda0289** [comment]
Thanks for the report.

Looks like the value of the literal node is `NaN`, which is a number, when it contains a regular expression. Looks like parser generates `null` and eslint converts it to `NaN`, but will try and get fix into next release.

**Comment by mdebruijne** [comment]
@soda0289 I have tested your change, works great, thanks a lot!
