### ISSUE TITLE
convert() logging node.kind to console

### ISSUE THREAD

**Issue by tomxtobin** [eslint/typescript-eslint-parser#29]
The `default` on `convert`'s `switch` on `node.kind` [logs it to the console][node-kind-log]. I understand that may be useful while hacking on the parser, but it's kinda distracting when trying to actually *use* the parser. :-)

Maybe this could be hidden behind a debug variable or configuration option?

[node-kind-log]: https://github.com/eslint/typescript-eslint-parser/blob/master/lib/ast-converter.js#L1378

**Comment by nzakas** [comment]
We should just remove it. I probably left it in there accidentally. :-X
