### ISSUE TITLE
Missing computed flag on TSMethodSignature

### ISSUE THREAD

**Issue by vjeux** [eslint/typescript-eslint-parser#290]
**What version of `typescript-eslint-parser` are you using?**
b7220fdbf5a923c64bb6e5bbbfc2ad689ec779eb

**What code were you trying to parse?**

```js
interface Iterable<T> {
  [Symbol.iterator](): Iterator<T>;
}
```

**What did you expect to happen?**

`TSMethodSignature` to have `computed: true`

**What happened?**

It doesn't.

```js
{ type: 'TSMethodSignature',
  range: [ 26, 59 ],
  loc: { start: { line: 2, column: 2 }, end: { line: 2, column: 35 } },
  transformFlags: undefined,
  modifiers: undefined,
  name:
   { type: 'MemberExpression',
     range: [ 27, 42 ],
     loc: { start: [Object], end: [Object] },
     object:
      { type: 'Identifier',
        range: [Object],
        loc: [Object],
        name: 'Symbol' },
     property:
      { type: 'Identifier',
        range: [Object],
        loc: [Object],
        name: 'iterator' },
     computed: false },
  questionToken: undefined,
  typeParameters: null,
  parameters: [],
  typeAnnotation:
   { type: 'TypeAnnotation',
     loc: { start: [Object], end: [Object] },
     range: [ 47, 58 ],
     typeAnnotation:
      { type: 'TSTypeReference',
        range: [Object],
        loc: [Object],
        transformFlags: undefined,
        typeName: [Object],
        typeParameters: [Object] } } }
```

So prettier prints it as

```js
interface Iterable<T> {
  Symbol.iterator(): Iterator<T>;
}
```

**Comment by soda0289** [comment]
Thanks for the report.

I think this is a duplicate of https://github.com/eslint/typescript-eslint-parser/issues/262

I have another PR https://github.com/eslint/typescript-eslint-parser/pull/264 that should handle all these cases. I will double check this one and add a test if needed.

**Comment by vjeux** [comment]
Awesome, looks like @azz already reported the same ones as I did :P

If you want to see what's missing to get all the popular typescript projects to transpile correctly: https://github.com/prettier/prettier/issues/1643#issuecomment-303602174

**Comment by vjeux** [comment]
This is actually not a duplicate of #262.

```js
var x: { [y]: any };
```

is now fixed, but

```js
interface Iterable<T> {
  [Symbol.iterator](): Iterator<T>;
}
```

is still missing `computed: true`

**Comment by vjeux** [comment]
Actually, nevermind. Prettier isn't printing it -_- but it's there!

**Comment by vjeux** [comment]
Okay, there are no longer any known issues with typescript-eslint-parser from prettier. You are awesome!

**Comment by azz** [comment]
Absolutely. Thanks heaps @soda0289 and @JamesHenry!
