### ISSUE TITLE
Any reason why TSUnionType is not UnionTypeAnnotation?

### ISSUE THREAD

**Issue by vjeux** [eslint/typescript-eslint-parser#294]
**What code were you trying to parse?**

```
type X = A | B;
```

**What did you expect to happen?**

For it to generate a `UnionTypeAnnotation`

**What happened?**

It generates a `TSUnionType`, with the exact same fields as `UnionTypeAnnotation`

**Comment by vjeux** [comment]
Other things I've had to duplicate:

```js
        n.type === "VoidTypeAnnotation" ||
        n.type === "TSVoidKeyword" ||
        n.type === "NullLiteralTypeAnnotation" ||
        (n.type === "Literal" &&
          n.value === null)
```

**Comment by soda0289** [comment]
We have plans to generate one AST for both babylon typescript plugin and this parser. In those discussions `TSUnionType` was recommend.
https://github.com/JamesHenry/tsep-babylon-test/issues/9#issuecomment-302175418

I don't think this changed has been made or finalized yet. Is `UnionTypeAnnotation` used by flow? I don't think we are going to go with `GenericTypeAnnotation` either will this be a problem?

**Comment by soda0289** [comment]
The next thing I spend time on will be cleaning up all the types and literals. I will create an issue in the next few days with ideas but I think we will be copying what Babylon does for the most part.

**Comment by vjeux** [comment]
I can (and already do) support both inside of prettier, so no real problem, but would be nice if flow and typescript would output the same type when possible.

**Comment by vjeux** [comment]
@thejameskyle, you've done some work in this area right?
 https://gist.github.com/thejameskyle/29555e16cbdc9bfad9a4d81a3df6aafd

**Comment by soda0289** [comment]
That looks like it could be very helpful, thanks!

**Comment by vjeux** [comment]
If you are interested, you can also look at the prettier source code. We now print all of TypeScript and Flow (via both babylon and the flow parser).

There are a handful of places where we use the same code to print the Flow and TypeScript nodes that could be merged: 
https://github.com/prettier/prettier/blob/9a93822bbceaa8585af4b0f7a68a1167834f32d1/src/printer.js#L461-L462

**Comment by thejameskyle** [comment]
TypeScript & Flow nodes should be given different types. I would go back and change all the flow stuff to: `FlowTypeAnnotation/FlowInterfaceDeclaration` if I could so you'd have:

- `FlowInterfaceDeclaration`
- `TypeScriptInterfaceDeclaration`

Then you could have them both aliased as `InterfaceDeclaration` and have all the `t.isInterfaceDeclaration` utils and you could still share code easily.

I don't think they should be merged though, they could be changed independently of one another.

**Comment by soda0289** [comment]
@thejameskyle We do try and prefix all typescript nodes with `TS`. There has been times where we do choose the same name and run into problems where typescript can behave differently. I will put some more thought into the benefit of using the same node type. I do agree that for most cases we should use our own node types.
