### ISSUE TITLE
Phase 3: Attach comments

### ISSUE THREAD

**Issue by nzakas** [eslint/typescript-eslint-parser#31]
Phase 3 is to add attaching leading/trailing comments to the AST inside the parser. This would involve:

1. Retrieving comments for each node.
1. Converting the TypeScript comments into Esprima-style comments.
1. Adding the comments into `leadingComments` and `trailingComments` arrays on appropriate nodes.
1. Making the result pass the tests that are already tests in tests/fixtures/attach-comments.

**Comment by nzakas** [comment]
astexplorer.net seems able to get leading and trailing comments for TypeScript, so it seems like there's probably already an API somewhere for getting that information. It might be worth looking at the astexplorer.net source for hints.

**Comment by JamesHenry** [comment]
As mentioned on gitter, I have made some decent progress on this. 9 test cases to go!
