### ISSUE TITLE
Support TypeScript 2.4

### ISSUE THREAD

**Issue by azz** [eslint/typescript-eslint-parser#321]
Main changes to syntax are dynamic imports and string enums. Both should probably "just work" by upgrading the `"typescript"` package.

https://blogs.msdn.microsoft.com/typescript/2017/06/12/announcing-typescript-2-4-rc/

**Comment by soda0289** [comment]
The biggest issue we encounter is when they changed the produced AST. I just tested out 2.4 and all our tests pass. Should be a painless upgrade.

**Comment by vjeux** [comment]
I also ran prettier tests on 2.4 and they all pass.

**Comment by vjeux** [comment]
Looks like there's no way to disable this warning though :( https://github.com/eslint/typescript-eslint-parser/blob/b7220fdbf5a923c64bb6e5bbbfc2ad689ec779eb/parser.js#L20-L33

I'd love if you could make a new commit with 2.4 support :)

**Comment by soda0289** [comment]
I'm not sure if we should change it to typescript 2.4 because then the warning will show when users run typescript 2.3.

We could disable the warning with an option or environment variable. We probably should not be using console.warn anyway and should allow for a logger to be overridden, since this is not a command line tool.

@JamesHenry What do you think should be done in this case?

**Comment by vjeux** [comment]
What about having a range of versions you support?

**Comment by vjeux** [comment]
A way to disable it without changing the code would be great though

**Comment by azz** [comment]
Semver `~2.3.2 || ~2.4`?

**Comment by JamesHenry** [comment]
It does seem a little strange to me to change to explicitly supporting a Release Candidate of an upcoming version... Supporting multiple _stable_ versions would be a different question, and perhaps one we should look into.

@azz @vjeux Even if prettier decides to jump straight into the RC before it is stable, I don't think we need to change things here.

Would you be happy with us exposing a way to suppress the warning as a way to solve this particular issue?

**Comment by JamesHenry** [comment]
Ha and of course as soon as I write that, it appears code changes are required to support 2.4 after all. I think we should maintain a 2.4 branch in parallel to master until it is stable. Then prettier can use that if it wants to

**Comment by azz** [comment]
Sounds good to me!

**Comment by JamesHenry** [comment]
This is the commit on the `ts-2.4` branch: `fcfc9579a01a39df1cd79fbb8304c43564a5f23b`

We can add in the logic to suppress/change the warning
