### ISSUE TITLE
typescript-eslint-parser fails on indent rule

### ISSUE THREAD

**Issue by ranzwix** [eslint/typescript-eslint-parser#33]
Hi,

We are running some tests to evaluate the usage of this parser in order to enable eslint in our typescript projects.
I am using master version and eslint 2.4.0.

I created a small repo which demonstrates our problem:
https://github.com/ranzwix/typescript-eslint-parser-check

It seems that the AST generated by the "code-sample.ts" file and the token-store are not aligned properly, therefore when getting to
"getNodeIndent" function, the code fails to find the appropriate token, and fails on the next line where
the method tries to access the undefined variable properties.
The instructions to run this example are in the repo itself.

Please note that the code passes OK if you remove that rule from the configuration file.

Best regards,
Ran

**Comment by nzakas** [comment]
Thanks. This parser isn't ready to be used yet, it's still very much experimental, so we aren't yet tackling ESLint bugs. See #13 for more details.

**Comment by nzakas** [comment]
Closing as we aren't accepting issues for ESLint rule bugs as they are not expected to work at this point.
