### ISSUE TITLE
consider working with babel-eslint and babylon with typescript support

### ISSUE THREAD

**Issue by graingert** [eslint/typescript-eslint-parser#335]
babylon now supports typescript out of the box: https://github.com/babel/babylon/pull/523

I think it's worth taking some time to consider working with babel-eslint and babylon to avoid duplication of effort.

**Comment by graingert** [comment]
See also https://github.com/JamesHenry/tsep-babylon-test

**Comment by JamesHenry** [comment]
Thanks, I'm very much aware, that's my repo after all 😜 I have been working with the TypeScript team directly on this for months. It is not yet time to consider deprecating this project but there may come a time in the future when it makes sense.
