### ISSUE TITLE
The AST does not contain a `comments` array at the root

### ISSUE THREAD

**Issue by j-f1** [eslint/typescript-eslint-parser#346]
**What version of TypeScript are you using?**
2.3.4

**What version of `typescript-eslint-parser` are you using?**
4.0.0

**What code were you trying to parse?**

```ts
// foo
```

**What did you expect to happen?**
The AST contains a `comments` array containing a node for the comment

**What happened?**
There is no `comments` array, so `eslint-plugin-import` breaks.

Example:

```js
const parser = require('typescript-eslint-parser/parser')
parser.parse('// foo')
// =>
{ type: 'Program',
  range: [ 6, 0 ],
  loc: { start: { line: 1, column: 6 }, end: { line: 1, column: 0 } },
  body: [],
  sourceType: 'script' }
```

**Comment by JamesHenry** [comment]
You need to specify that you want comments to be collected within the parser options:

```javascript
parser.parse('// foo', { comment: true })
```

**Comment by j-f1** [comment]
`espree` uses `attachComment`, so shouldn’t this repo do the same for cross-compatibility?

**Comment by JamesHenry** [comment]
These are the relevant options within espree:

```js
// create a top-level comments array containing all comments
comment: false,

// attach comments to the closest relevant node as leadingComments and trailingComments
attachComment: false
```

`comment` is the option which addresses this issue, `attachComment` is no longer relevant for this parser as we made the decision a while ago to move comment attribution into ESLint itself.

See this PR if you are interested in all of the background to that: https://github.com/eslint/eslint/pull/7516
