### ISSUE TITLE
Support TypeScript 2.5

### ISSUE THREAD

**Issue by azz** [eslint/typescript-eslint-parser#368]
https://blogs.msdn.microsoft.com/typescript/2017/08/17/announcing-typescript-2-5-rc/

- [x] Optional Catch Binding

**Comment by JamesHenry** [comment]
Anyone wishing to use 2.5 before it is the stable release can install the latest git commit from this PR: https://github.com/eslint/typescript-eslint-parser/pull/370

**Comment by azz** [comment]
https://blogs.msdn.microsoft.com/typescript/2017/08/31/announcing-typescript-2-5/

**Comment by donaldpipowitch** [comment]
I couldn't found any errors with 2.5 so far :+1:
