### ISSUE TITLE
never keyword's type is not forwarded

### ISSUE THREAD

**Issue by azz** [eslint/typescript-eslint-parser#380]
**What version of TypeScript are you using?**

2.5.1

**What version of `typescript-eslint-parser` are you using?**

ts-2.5 branch

**What code were you trying to parse?**

```
Observable.empty<never>();
```

**What did you expect to happen?**

`"type": "TSNeverKeyword"`

**What happened?**

no `type` property on the node.

Ref: https://github.com/prettier/prettier/issues/2718

**Comment by JamesHenry** [comment]
This has now been fixed, thanks @azz
