### ISSUE TITLE
Breaking Change to lots of AST node types for TypeScript constructs 

### ISSUE THREAD

**Issue by JamesHenry** [eslint/typescript-eslint-parser#386]
Follow up to https://github.com/babel/babylon/pull/710

cc @soda0289 @azz @weirdpattern

I should hopefully get to this this week.

**Comment by JamesHenry** [comment]
Just in case anybody else looks at this, be sure to run:

`yarn ast-alignment-tests`

It will run the comparisons between Babylon and typescript-eslint-parser

**Comment by hzoo** [comment]
Should just be 4 based on https://github.com/babel/babel/pull/6306,

TypeParameter
TypeParameterInstantiation
TypeParameterDeclaration
TypeParameter

**Comment by JamesHenry** [comment]
Actually I'll work on this now
