### ISSUE TITLE
Call for help @ Goodness Squad X

### ISSUE THREAD

**Issue by mightyiam** [eslint/typescript-eslint-parser#391]
I'll be rallying this project and [eslint-plugin-typescript](https://github.com/nzakas/eslint-plugin-typescript) at an open source contributing session, [Goodness Squad X](https://www.meetup.com/JavaScript-Israel/events/244024753/), October 18 (8 days from today), Tel Aviv, Israel, hosted by Wix.

I see this as a good way to promote these libraries in terms of usage and contribution. A happy contributor is a returning contributor :rose:.

I can use some help getting more familiar with the code here and in the plugin, prior to that. The more I know, the more I can help the participants in their contributions.

I encourage any kind of help, including:
- give me a 1 on 1 session exploring the codebase ( :boom: :+1: :fireworks: :tada: ) this would be perfect.
- more documentation on contributing (if I get the above mentioned session, I will write this documentation)
  - how to report a bug here and in the plugin
  - how to create a minimal—failing test—PR here and in the plugin
  - plugin: how to write a rule that fixes/replaces an ESLint core rule
- Online availability of contributors who are able to support participants will be super extra appreciated. Even only as responding quickly to issues and PRs during the time of the event.
- Attend the event physically (I'm pretty sure there will be free food and drinks).

**Comment by ilyavolodin** [comment]
@mightyiam Thanks for your interest in the project. Both of the maintainers of this repository are currently on vacation, so it might take a little while till you get a response.

**Comment by JamesHenry** [comment]
Hi @mightyiam, I am really sorry that due to the timing we weren't able to make this happen!

I hope the event was amazing, it's a really great initiative.

**Comment by mightyiam** [comment]
Thanks, @JamesHenry. Actually, while at previous occurrences we had close to 50 participants, this time it was around 15. And it so happened that none have participated in contributing to this particular project.

I have struggled to find a project that I'm interested in and that would be fast and relatively easy to start contributing to immediately, without prior acquaintance. This fits the bill. So maybe next time. It seems that you're willing to participate in some manner, @JamesHenry, so I'll post again next time.

Thanks!
