### ISSUE TITLE
Support TypeScript 2.6

### ISSUE THREAD

**Issue by OliverJAsh** [eslint/typescript-eslint-parser#394]
TypeScript 2.6 is now in RC. https://blogs.msdn.microsoft.com/typescript/2017/10/12/announcing-typescript-2-6-rc/

I'm not sure if we need to change anything in the parser, but at the very least we can update the supported version notice.

**Comment by JamesHenry** [comment]
Yep, seems all good thanks @OliverJAsh!

I have opened a PR so you can start using that if you wish, I will keep it synced with master as usual.
