### ISSUE TITLE
Type annotations being caught by space-infix-ops rule

### ISSUE THREAD

**Issue by JamesHenry** [eslint/typescript-eslint-parser#4]
(Note: I am using ESLint via eslint-loader for webpack)
ESLint: 1.9.0
eslint-loader: 1.1.1
typescript-eslint-parser: 0.1.0-alpha-1

The following code shows how a variable, `foo`, can be explicitly annotated with type `string`
`let foo: string = 'bar'`

Currently this causes the `space-infix-ops` rule to error (if enabled).

Re-writing to:
`let foo : string = 'bar'`

...does fix the eslint error, and is technically not a TypeScript error [(example)](http://www.typescriptlang.org/Playground/#src=let%20foo%20%3A%20string%20%3D%20'bar').

However, I would argue that the vast majority of people write their annotations using the first form, and that is certainly what comes through in all the documentation and examples from Microsoft.

It would therefore not be the intention of users who have enabled the `space-infix-ops` rule to receive an error for `let foo: string = 'bar'`

**Comment by nzakas** [comment]
Rules are going to behave strangely with TypeScript for a while; it's too early to start getting into making all the rules work (or making any changes to allow that). 

In any event, there's nothing the parser could do to fix this, it would have to be some option in ESLint. Once the parsing is working correctly and the AST is filled out completely, we can circle back and look at what (if anything) can be done for failing rules.

**Comment by JamesHenry** [comment]
Ok, that makes sense. Are there any resources you can point me at to get up to speed more quickly with how the AST is built, terminology etc?

I am super keen to help ESLint be a viable option for Angular 2 development, in particular, as I think we will be seeing a whole new wave of devs/teams embracing TypeScript, but I currently have no experience with linters/ASTs and would appreciate any ProTips!

**Comment by ilyavolodin** [comment]
[SpiderMonkey Parser API](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API)
[Espree demo](http://eslint.org/parser/)
[Working with ESLint Rules](http://eslint.org/docs/developer-guide/working-with-rules)
That should get you started.

**Comment by JamesHenry** [comment]
Many thanks, @ilyavolodin!

**Comment by nzakas** [comment]
https://GitHub.com/ESTree/estree

**Comment by alberto** [comment]
Thanks @nzakas, that's super useful!

**Comment by mysticatea** [comment]
http://astexplorer.net/

**Comment by JamesHenry** [comment]
:+1:

**Comment by Pleasurazy** [comment]
Hi, Is this issue have any update?

**Comment by nzakas** [comment]
@Pleasurazy the issue is closed. This project is still experimental and is expected to have a lot of errors at this point. As such, we are not accepting bug reports at this time.

**Comment by AdamWillden** [comment]
As this parseris now at 1.0.0 are we free to submit bug reports such as this? Can this be reopened?

**Comment by JamesHenry** [comment]
@AdamWillden it is not a bug in this project (i.e. it is not problem with the parsing or the generated AST), so this will not be reopened.

The rule in ESLint core will need to be extended to take typeAnnotation nodes into account, as mentioned here https://github.com/eslint/typescript-eslint-parser/issues/77#issuecomment-244426469

**Comment by AdamWillden** [comment]
@JamesHenry thanks for linking the two. Makes sense!
