### ISSUE TITLE
array-callback-return TypeError

### ISSUE THREAD

**Issue by pat841** [eslint/typescript-eslint-parser#400]
**What version of TypeScript are you using?**
2.5.3

**What version of `typescript-eslint-parser` are you using?**
8.0.1

**What code were you trying to parse?**
```javascript
export abstract class TestAbstract {

  onCreated?(): Promise<void> | any;

}
```

**What did you expect to happen?**
ESLint shouldnt fail when parsing the file.

**What happened?**
`TypeError: Cannot read property 'type' of null`
`node_modules/eslint/lib/rules/array-callback-return.js:194:34`

If I add a function body, it works:
```javascript
  onCreated(): Promise<void> | any {

  }
```

**Comment by JamesHenry** [comment]
Thanks @pat841, this is the same issue around TS function constructs not having a body interfering with expectations in ESLint rules. We are discussing the best way to address this right now
