### ISSUE TITLE
 Parsing error when using union types

### ISSUE THREAD

**Issue by ibufu** [eslint/typescript-eslint-parser#403]
**What version of TypeScript are you using?**
v2.5.3

**What version of `typescript-eslint-parser` are you using?**
latest

**What code were you trying to parse?**

```js
data() {
    return {
      form: {
        startDate: <Date | undefined> undefined
      }
    };
}
```

**What did you expect to happen?**

**What happened?**

parsing error.

**Comment by JamesHenry** [comment]
@ibufu do you have `jsx: true` in your parserOptions? That is the only way I can reproduce this.

Please see https://github.com/eslint/typescript-eslint-parser/issues/399 for more information about this. Essentially when `jsx: true`, you cannot use ambiguous TS constructs such as the `<>` syntax for type assertions. You could refactor your code to use the `as` syntax instead.

I will close this out for now, but please let me know if my assumption about you using jsx is not accurate.
