### ISSUE TITLE
Recursive file search breaks

### ISSUE THREAD

**Issue by corbinu** [eslint/typescript-eslint-parser#419]
**What version of TypeScript are you using?**
2.6.2

**What version of `typescript-eslint-parser` are you using?**
9.0.1

**What code were you trying to parse?**
All my projects

**What did you expect to happen?**
Just noticed this when switching TypeScript on in a module I had previously written in JavaScript. I use `eslint src/**/*` to run my tests and I expect them to run on all directories recursively like they normally do 

**What happened?**
Only files in the src directory or one level down are tested so for example src/lib/models.ts and src/index.ts test just fine. However the next set down doesn't get tested. For example src/lib/controllers/index.ts. If I change to `eslint src/**/* src/lib/**/*`. The files are tested but again only for one more level down.

**Comment by JamesHenry** [comment]
Please can you provide a minimal reproduction of the issue?

**Comment by corbinu** [comment]
@JamesHenry I looked back at my other TS projects and is occurring on all of them will see what I can whip up in a repo

**Comment by corbinu** [comment]
@JamesHenry Here you go 

https://github.com/corbinu/typescript-eslint-recursive-example

If I remove the typescript parser, interfaces and change them to .js I get 
```
typescript-eslint-recursive-example@0.0.1 lint /Users/corbinu/Developer/git/typescript-eslint-recursive-example
> eslint src/**/*


/Users/corbinu/Developer/git/typescript-eslint-recursive-example/src/one/lintedmessage.js
  1:53  error  Missing semicolon  semi

/Users/corbinu/Developer/git/typescript-eslint-recursive-example/src/one/two/notlintedmessage.js
  1:65  error  Missing semicolon  semi
```
but when I am using the parser I just get
```
/Users/corbinu/Developer/git/typescript-eslint-recursive-example/src/one/lintedmessage.ts
  1:53  error  Missing semicolon                         semi
  3:11  error  An empty interface is equivalent to `{}`  typescript/no-empty-interface
```

**Comment by corbinu** [comment]
If I switch to `eslint src --ext .ts` it works fine which is very interesting. Looking through the code I am wondering if this is actually an issue in eslints custom parser handling not specifically the typescript parser

**Comment by JamesHenry** [comment]
@corbinu Did you take this any further regarding the core ESLint issue?

**Comment by platinumazure** [comment]
@corbinu Try quoting the globs-- maybe your shell is getting in the way?

**Comment by corbinu** [comment]
@JamesHenry No I just been using the different syntax. I will try to take a better look this weekend. The example still fails though

@platinumazure If it was the shell then why would it only be an issue with the typescript parser?

**Comment by platinumazure** [comment]
Just a guess: Because the shell might have decided to return directories
only, for some reason, so ESLint only received directories and then applied
the --ext rules?

**Comment by corbinu** [comment]
Hmm interesting well I am using zsh I will test on the example in bash later

**Comment by JamesHenry** [comment]
I'm going to close this due to lack of activity.

We now have a brand new way of running integration tests for this project, which allows for complex setups to be reproduced in isolation: https://github.com/eslint/typescript-eslint-parser#integration-tests

If this is still an issue for you using the latest version, please create a failing integration test for it and open a new issue to discuss.

Thanks!
