### ISSUE TITLE
Definite assignment assertions not in AST

### ISSUE THREAD

**Issue by azz** [eslint/typescript-eslint-parser#424]
**What version of TypeScript are you using?**
` typescript@2.7.0-dev.20171224`

**What version of `typescript-eslint-parser` are you using?**
`master`

**What code were you trying to parse?**

```ts
class X { a!: any }
```

**What did you expect to happen?**
Something like `definite: true` or `exclamationToken: true` in the AST. In the TS AST it is called `exclamationToken`.

New in https://github.com/Microsoft/TypeScript/pull/20166

**What happened?**

```js
{
  type: 'ClassProperty',
  range: [ 10, 17 ],
  loc: {...},
  key:  {...},
  value: null,
  computed: false,
  static: false,
  readonly: undefined,
  typeAnnotation:  {...}
}
```

Thoughts on which property name to go for?

**Comment by sgoll** [comment]
I'd go with `exclamationToken` for two reasons:
1) The parser should IMHO add as little additional interpretation (i.e. semantics) as possible, and for now the exclamation mark token might mean "definite" but this may change or broaden at some later point.
2) The TS AST calls it `exclamationToken` and sticking to the same name avoids confusion.

**Comment by JamesHenry** [comment]
For me the parallel with `optional` (coming from `questionToken` in the original TS AST) is very strong.

As per Nicolo's comment here: https://github.com/babel/babel/pull/7159#discussion_r160026875

**Comment by JamesHenry** [comment]
@sgoll We will definitely be going for whatever is agreed on that babylon PR to stay aligned, so if you feel strongly about it either way please add to the discussion on there. Thanks!

**Comment by sgoll** [comment]
@JamesHenry Done that, and you are right, of course—the parallel with `optional` is strong.
