### ISSUE TITLE
Support `unique symbol` type (TS 2.7)

### ISSUE THREAD

**Issue by ikatyang** [eslint/typescript-eslint-parser#426]
**What version of TypeScript are you using?**
typescript@2.7.0-dev.20171226

**What version of `typescript-eslint-parser` are you using?**
eslint/typescript-eslint-parser#e94ede3

**What code were you trying to parse?**

```ts
type A = unique symbol;
type B = keyof something;
```

**What did you expect to happen?**
```json5
[
  { "type": "TSTypeOperator", "operator": "TSUniqueKeyword" },
  { "type": "TSTypeOperator", "operator": "TSKeyOfKeyword"  },
]
```

**What happened?**
```json5
[
  { "type": "TSTypeOperator", "operator": 140 },
  { "type": "TSTypeOperator", "operator": 127 },
]
```

Ref: https://github.com/Microsoft/TypeScript/pull/15473

**Comment by JamesHenry** [comment]
Thanks for reporting, and thanks again @azz for already kicking off the PR

**Comment by donaldpipowitch** [comment]
2.7 is now the stable release 💕

**Comment by JamesHenry** [comment]
Merged 👍
