### ISSUE TITLE
Rename ExperimentalSpreadProperty

### ISSUE THREAD

**Issue by duailibe** [eslint/typescript-eslint-parser#428]
**What version of TypeScript are you using?**

2.6.2

**What version of `typescript-eslint-parser` are you using?**

master

**What code were you trying to parse?**

```ts
const foo = { ...bar };
```

**What did you expect to happen?**

An `SpreadElement` or `SpreadProperty` should be in the AST, not `ExperimentalSpreadProperty`, since they are not considered experimental anymore (https://github.com/Microsoft/TypeScript/commit/39b9163715fac6975c5691ae4d85afbc2eabcb62)?

I'm not exactly sure how this should go but would make things a lot easier to maintain in prettier (for example https://github.com/prettier/prettier/pull/3681) :-)

I can help with this, just need a direction (cc @JamesHenry)

**Comment by JamesHenry** [comment]
Thanks @duailibe! As now discussed on the PR, currently ESLint's policy dictates that because this is only stage 3, it is still experimental.
