### ISSUE TITLE
[Not a issue] is there a estree-like documentation for typescript?

### ISSUE THREAD

**Issue by bendtherules** [eslint/typescript-eslint-parser#448]
Is there a typescript AST specification documented (similar to es-tree) in this project/somewhere else?

Looked through the source here, but couldn't find anything concrete. Saw a few grouping of related syntax types. Or is it really not much needed as ts ast nodes are already typed?

Some guidance will be helpful

**Comment by JamesHenry** [comment]
At the moment, I do not have time to create something like this and I am fairly certain one does not exist. My favourite way to check out ASTs is to use http://astexplorer.net, I would highly recommend checking it out if you haven't before!
