### ISSUE TITLE
space-infix-ops fails for mapped type declarations

### ISSUE THREAD

**Issue by nevir** [eslint/typescript-eslint-parser#449]
**What version of TypeScript are you using?**

2.7.1

**What version of `typescript-eslint-parser` are you using?**

14.0.0

**What code were you trying to parse?**

```ts
export type FieldArguments<TArgTypes = JsonScalar> = NestedObject<TArgTypes>;
```

**What did you expect to happen?**

No error with `space-infix-ops: error`

**What happened?**

`Infix operators must be spaced`

**Repro**

If you check out https://github.com/convoyinc/apollo-cache-hermes, and uncomment [the `space-infix-ops` rule](https://github.com/convoyinc/apollo-cache-hermes/blob/master/.eslintrc.yml#L136), it'll generate this error at a few locations

**Comment by JamesHenry** [comment]
I think a custom rule may need to be created in the [plugin](https://github.com/nzakas/eslint-plugin-typescript) to handle this. It would be fantastic if one of the people affected by this issue could contribute to it.

**Comment by zuzusik** [comment]
@JamesHenry looks like it is issue of a parser - I did a quick search over the code and looks like the support of `GenericTypeAnnotation` which was added here https://github.com/eslint/typescript-eslint-parser/pull/53/files#diff-6ecca2b7675f672f87297d93eec1e4baR479 was dropped at some point

I assume the fix would be get back the support of `GenericTypeAnnotation` in this parser

**Comment by madbence** [comment]
@nevir @JamesHenry eslint/eslint#10935 was merged, so i think this can be closed. 🙆

**Comment by mysticatea** [comment]
Thank you!
