### ISSUE TITLE
How to best traverse the AST using a visitor pattern?

### ISSUE THREAD

**Issue by kristianmandrup** [eslint/typescript-eslint-parser#451]
Not clear how to best traverse the AST using a visitor pattern and not specifically to make rules for linting?

Found a few potentially useful libs, but not clear which are compatible with ESTree??

- [eslint-traverser](https://github.com/ganimomer/eslint-traverser) 
- [estraverse-fb](https://www.npmjs.com/package/estraverse-fb)
- [ast-traverse](https://www.npmjs.com/package/ast-traverse)
- [esprima-walk](https://www.npmjs.com/package/esprima-walk)
- ...

There are also the more generic approaches...

- [json-query](https://www.npmjs.com/package/json-query)
- [traverse](https://www.npmjs.com/package/traverse)
- ...

Perhaps I need to build my own??

**Comment by JamesHenry** [comment]
Please checkout the [plugin](https://github.com/nzakas/eslint-plugin-typescript) for how this works in practice, best of luck!
