### ISSUE TITLE
Support TaggedTemplateExpression typeParameters (TS 2.9)

### ISSUE THREAD

**Issue by ikatyang** [eslint/typescript-eslint-parser#468]
**What version of TypeScript are you using?**
2.9.0-dev.20180421

**What version of `typescript-eslint-parser` are you using?**
14.0.0

**What code were you trying to parse?**

```ts
export const RedBox = styled.div<{foo: string}>`
  background: red;
  ${props => props.foo}
`;
```

**What did you expect to happen?**
`typeParameters` exists in `TaggedTemplateExpression` node.

**What happened?**
`typeParameters` is missing.

**Comment by JamesHenry** [comment]
Support has been merged into master
