### ISSUE TITLE
TSTypeReference does not emit for React.SFC 

### ISSUE THREAD

**Issue by milesj** [eslint/typescript-eslint-parser#476]
**What version of TypeScript are you using?**

2.8.1

**What version of `typescript-eslint-parser` are you using?**

0.12.0

**What code were you trying to parse?**

```ts
export interface PriceProps {
  // Some props
}

export const Price: React.SFC<PriceProps> = function Price(props) {}
```

**What did you expect to happen?**

I'm trying to write a rule that verifies the generics in `React.SFC` are correct, however, the `TSTypeReference` for `React.SFC` is never emitted, so I'm unable to capture and and write a rule around it.

For example, this doesn't even log.

```
TSTypeReference(node) {
  console.log(node);
},
```

**What happened?**

Doesn't work.

**Comment by macklinu** [comment]
I'm wondering if this issue is related to what's blocking https://github.com/nzakas/eslint-plugin-typescript/pull/117.

**Comment by milesj** [comment]
Sounds like it. I've noticed that if I go up to the parent, I can see the `TSTypeReference` node correctly as a child. It just doesn't work when referencing it directly.
