### ISSUE TITLE
Identifier used as type definition is recognised as unused

### ISSUE THREAD

**Issue by OliverJAsh** [eslint/typescript-eslint-parser#48]
Hi, thanks for your amazing work. I have some feedback but I am very aware this project is still in the very early stages.

When I import an identifier and use it only as a type definition, the parser considers the identifier as unused. It is in fact unused in the JS, but used in the TS. I'm not sure how the parser should handle this?

Versions:

```
$ npm ls eslint typescript-eslint-parser
/Users/OliverJAsh/Development/samefourchords.com
├── eslint@3.0.1
└── typescript-eslint-parser@0.1.0-alpha-1
```

ESLint config:

``` json
{
    "extends": "eslint:recommended",
    "parser": "typescript-eslint-parser",
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "modules": true
        }
    }
}
```

Input and output:

```
$ echo "import { Post } from './models'; let post: Post; post;" > test.js
$ eslint test.js

/Users/OliverJAsh/Development/samefourchords.com/test.js
  1:10  error  'Post' is defined but never used  no-unused-vars
```

**Comment by nzakas** [comment]
Sorry, same response as here: https://github.com/eslint/typescript-eslint-parser/issues/47#issuecomment-233098147

**Comment by OliverJAsh** [comment]
Hi, this still appears to be an issue. Do you know whether this is something we can fix? Keen to help :-)
