### ISSUE TITLE
no-unused-vars should understand imported type usage

### ISSUE THREAD

**Issue by Snugug** [eslint/typescript-eslint-parser#488]
**What version of TypeScript are you using?**
2.9.1

**What version of `typescript-eslint-parser` are you using?**
16.0.0

**What code were you trying to parse?**

```ts
import { Application } from 'express';

app().then((server:Application) => {

});
```

**What did you expect to happen?**
With rule `no-unused-vars`, I expect `Application` to come back as being used as it's being imported and used as a type

**What happened?**
`  1:10  error  'Application' is defined but never used  no-unused-vars`

**Comment by st-sloth** [comment]
This issue duplicates #457 that is closed because this problem is not a parsing but a rule issue.

**Comment by armano2** [comment]
To make it work i suggest using https://github.com/bradzacher/eslint-plugin-typescript/blob/master/docs/rules/no-unused-vars.md

**Comment by JamesHenry** [comment]
Using the plugin probably makes the most sense here, ESLint will not be able to understand many TS specific concerns natively.

Please feel free to open any other issues on the new project https://github.com/typescript-eslint/typescript-eslint

Thanks!
