### ISSUE TITLE
Generic type on a method is throwing a parsing error

### ISSUE THREAD

**Issue by Kocal** [eslint/typescript-eslint-parser#497]
Hello, 

I'm migrating my code base to the new vue-cli tooling, and I encountered an issue when running ESLint on TypeScript code that use a generic type. :disappointed: 

If it can help, I'm using [`@vue/cli-plugin-eslint`](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-eslint) and [`@vue/eslint-config-typescript`](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/eslint-config-typescript).
Here is my `.eslintrc.js`:

```js
module.exports = {
  root: true,
  env: {
    node: true
  },
  'extends': [
    'plugin:vue/recommended',
    '@vue/prettier',
    '@vue/typescript',
  ],
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'on' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'on' : 'off',
  }
};
```

**What version of TypeScript are you using?**

Version 2.9.2 and 3+

**What version of `typescript-eslint-parser` are you using?**

Version 16.0.1

**What code were you trying to parse?**

```ts
export const decorateRequest = <T>(request: Promise<T>, bag: RequestBag): Promise<T> => {
  Object.assign(bag, makeRequestBag());

  return new Promise<T>(resolve => {
    // ...
  });
};
```

**What did you expect to happen?**

No errors 

![capture d ecran de 2018-07-14 21-47-37](https://user-images.githubusercontent.com/2103975/42727954-d64b945a-87af-11e8-84ae-7871477fdc8c.png)

For having this result, I changed my code to:

```diff
-export const decorateRequest = <T>(request: Promise<T>, bag: RequestBag): Promise<T> => {
+export const decorateRequest = (request: Promise<any>, bag: RequestBag): Promise<any> => {
  Object.assign(bag, makeRequestBag());

  return new Promise<T>(resolve => {
    // ...
  });
};
```

**What happened?**

![capture d ecran de 2018-07-14 21-45-38](https://user-images.githubusercontent.com/2103975/42727948-c888a970-87af-11e8-9c8c-34172bd14cd9.png)

When using AST explorer with `typescript-eslint-parser`, my code is not parsed: https://astexplorer.net/#/gist/c19d736c02a606dc437892e2ba502ab6/2cf1e76e411f75f6aa7c94328724b8e7fa504611

![capture d ecran de 2018-07-14 21-57-41](https://user-images.githubusercontent.com/2103975/42727994-f87958e0-87b0-11e8-8365-513c8b72dc0d.png)

But when I change to `typescript`, it's working: http://astexplorer.net/#/gist/c19d736c02a606dc437892e2ba502ab6/fde12f491295d79d28c9d05e02486734932fb3a0

Tell me if you need more info, I will be glad to help you to solve this bug :+1: 
Thanks

**Comment by GuoQichen** [comment]
same problem with vue-cli3

**Comment by JamesHenry** [comment]
Is one or more of those configs being extended setting `jsx: true`?

If so it is highly likely: https://github.com/eslint/typescript-eslint-parser/issues/517

**Comment by mysticatea** [comment]
Closing as favor of #517. Thank you.
