### ISSUE TITLE
Great work - Q: Will I be able to use eslint rules (eslint-config-hapi ) on a typescript project with this

### ISSUE THREAD

**Issue by mmc41** [eslint/typescript-eslint-parser#51]
I am very happy that you are going to support typescript. Specifically, I am looking for a way to check if a hapijs project in typescript conforms to the hapijs code standards as formulated by the "eslint-config-hapi" npm module. Will this project be able to do that ?

**Comment by ilyavolodin** [comment]
@mmc41 This project is in the very early stages yet, eventually - yes, the idea would be to be able to reuse eslint rules/configs for typescript. It's too early to say if all of the ESLint rules will work for TypeScript.

**Comment by nzakas** [comment]
There's no reason that shouldn't work in the future. Either the core ESLint rules will work or you'll be able to write your own rules to do whatever you want.

**Comment by mmc41** [comment]
Great. It would be nice if just eslint rules for typescript is a superset of eslint rules for javascrupt - just like typescript is a superset of javascript. Then the eslint-config-hapi should work out of the box.
