### ISSUE TITLE
Jest tests seem to be failing

### ISSUE THREAD

**Issue by uniqueiniquity** [eslint/typescript-eslint-parser#513]
**What version of TypeScript are you using?**
3.0.3

**What version of `typescript-eslint-parser` are you using?**
18.0

**What were you trying to do?**
Checkout `master` and run `node .\node_modules\jest\bin\jest.js`

**What did you expect to happen?**
Tests pass

**What happened?**
2 snapshots failed (both `tsx.js` tests).

**Comment by JamesHenry** [comment]
Please try again @uniqueiniquity, the most recent master build passed just now, and the project has undergone some significant changes.

Thanks!

**Comment by uniqueiniquity** [comment]
Oh man, that is a big change 😰 Thanks!
