### ISSUE TITLE
Make eslint a peer dependency

### ISSUE THREAD

**Issue by patsissons** [eslint/typescript-eslint-parser#523]
`typescript-eslint-parser` is now pulling in `eslint@4.19.1`, ideally it should be asking for a peer dependency of `"eslint": ">=4.19.1"`. This would allow de-duplication of the eslint dependency in consumers of `typescript-eslint-parser` using a different version of `eslint`.

A current workaround is to pin the `eslint` dependency in a consuming project using a resolution. For example, to force using `eslint@^5.0.0`

```json
"resolutions": {
  "eslint": "^5.0.0",
}
```

**Comment by milesj** [comment]
+1

**Comment by platinumazure** [comment]
I agree that ESLint should probably not be a dependency anymore in this project. I'll try to take a look at fixing this week.
