### ISSUE TITLE
[Feature request] Support TS ~3.1.0

### ISSUE THREAD

**Issue by kaelig** [eslint/typescript-eslint-parser#524]
Thanks to all the contributors for the awesome package ❤️ 

TypeScript 3.1 fixes a large number of bugs and regressions. It'd be great if this parser supported it 🙏

**Comment by Coder-256** [comment]
@JamesHenry

**Comment by brunolemos** [comment]
We may soon add this to [create-react-app](https://github.com/facebook/create-react-app/pull/4837), it would be preferable to add with the latest typescript version instead of 3.0.1.

**Comment by outofambit** [comment]
`typescript-estree` officially supports TS3.1! https://github.com/JamesHenry/typescript-estree/pull/14

**Comment by brunolemos** [comment]
Just an update about [create-react-app](https://github.com/facebook/create-react-app/pull/4837), the maintainers asked to remove this from the pull request since there is a big `help wanted` in the readme, which shows that this will probably give maintainability burden for them in the future.
