### ISSUE TITLE
Problem with Interfaces

### ISSUE THREAD

**Issue by gaurav21r** [eslint/typescript-eslint-parser#75]
**What version of TypeScript are you using?** **1.8.10**

**What version of `typescript-eslint-parser` are you using?**  **0.2.0**

**What code were you trying to parse?**

```js
interface Iwhen {
  (config: Object, thenFunc: Function): any,
  _eventHandlers: Object,
  _attributeHandlers: Array <Object>,
  _propertyListeners: Array <Object>,
  _mutationObserver: MutationObserver
}
```

**.eslintrc**
```
{
  "extends": "airbnb",
  "parser": "typescript-eslint-parser"
}
```

**What did you expect to happen?**
From what I could gather from #74 , I should be able to get Linted with no Errors

**What happened?**

```
  1:11  error  'Iwhen' is not defined               no-undef
  3:4   error  'config' is not defined              no-undef
  3:20  error  'thenFunc' is not defined            no-undef
  4:3   error  '_eventHandlers' is not defined      no-undef
  5:3   error  '_attributeHandlers' is not defined  no-undef
  6:3   error  '_propertyListeners' is not defined  no-undef
  7:3   error  '_mutationObserver' is not defined   no-undef
  7:22  error  'MutationObserver' is not defined    no-undef

```

**Comment by platinumazure** [comment]
I *did* [say](https://github.com/eslint/typescript-eslint-parser/issues/74#issuecomment-243587272) "when this project is ready". :smile:

I don't know if we've even gotten to interfaces yet.

**Comment by nzakas** [comment]
@gaurav21r I appreciate the enthusiasm, but please note what it says on the readme:

> ## Reporting Bugs
>
> **Do not** file bugs about ESLint rule failures. This is expected because ESLint doesn't know anything about TypeScript syntax. It's likely that many ESLint rules will have failures as a result. Longer-term, it's likely we'll need to create a custom set of ESLint rules that are TypeScript-specific.
>
> Bugs should be filed for:
> 
> 1. TypeScript syntax that fails to parse.
> 1. TypeScript syntax that produces an unexpected AST.

We are still very far away from having all ESLint rules work, and from having ESLint know how to interpret TypeScript-specific syntax.

**Comment by trusktr** [comment]
Hello, how can I work around the error

```
  ✘  http://eslint.org/docs/rules/no-undef                'NodeListOf' is not defined
  src/util.ts:10:60
      const links = document.querySelectorAll( selector ) as NodeListOf<HTMLElement>
```

? Do I have to use a comment to tell eslint to ignore that error on that line? Is there any other workaround?
