### ISSUE TITLE
Reason for the BSD-2 License

### ISSUE THREAD

**Issue by simondiep** [eslint/typescript-eslint-parser#84]
Is there a specific reason this project uses the BSD-2 license?  That's a limiting factor for me.

**Comment by nzakas** [comment]
Can you explain the limiting factor?

Generally, all of our projects are either MIT or BSD-2. In this case, there's parser code from another project that's licensed under BSD-2, so we just kept the same license.

**Comment by simondiep** [comment]
Is there a specific npm dependency that is BSD-2?

I'm currently not allowed to use BSD-2 licensed projects.

**Comment by nzakas** [comment]
I don't know if any dependencies are BSD-2 or not, we only require dependencies to have a liberal open source license.

Can you explain why you can't use BSD-2? This is generally one of the safest open source licenses.

Also, the open source license only applies to modifying the code, not using it, so if you're only interested in using the code then there shouldn't be a problem.
