### ISSUE TITLE
ClassProperty and MethodDeclaration Visibility Declarations

### ISSUE THREAD

**Issue by dannyfritz** [eslint/typescript-eslint-parser#87]
**What version of TypeScript are you using?**
2.0.2

**What version of `typescript-eslint-parser` are you using?**
0.2.0

**What code were you trying to parse?**

```
class Animal {
  public name: string
}
```

**What did you expect to happen?**
I expected an `ASTNode` for `ClassProperty` with `public` represented on it.

**What happened?**
I had to use [`context.getText(node)`](https://github.com/dannyfritz/eslint-plugin-typescript/blob/5c9bff1197fb65f766f5f18020f99c23bb71aa23/lib/rules/member-access.js#L49) to do a string find for the [visibility declaration](https://www.typescriptlang.org/docs/handbook/classes.html#public-private-and-protected-modifiers). I'm wondering if I either missed something or if we are missing it in the conversion.

---

References this PR on the `typescript-plugin` https://github.com/nzakas/eslint-plugin-typescript/pull/4#issuecomment-246378378

**Comment by nzakas** [comment]
The `public` is represented in the  TypeScript AST, we just aren't converting it.

**Comment by dannyfritz** [comment]
I'll take another look later today because I was looking in the TS AST I thought for it. Could you be more specific? Or is there a handbook for the TS AST somewhere? Otherwise I'll just take a more scrutinous look later today.

**Comment by nzakas** [comment]
I just used astexplorer.net with your example

**Comment by dannyfritz** [comment]
I can work on this.

Also thanks for `astexplorer.net`. This is a great tool.

**Comment by nzakas** [comment]
Cool!

I think we probably just want to add a `visibility` property to the `ClassProperty` and `MethodDefinition` nodes, with a possible value of `null` (if not present), `"private"`, or `"public"`.

**Comment by dannyfritz** [comment]
I was thinking about putting it under `modifiers` as that is what TS AST seems to do.

![screen shot 2016-09-14 at 12 11 54](https://cloud.githubusercontent.com/assets/315788/18524141/7ca50818-7a74-11e6-9c03-9002107c68e2.png)

---

I'm having some trouble figuring out the tests. Quite a few of the JSX ones are failing for me out of the gate which I assume is known. Using `TS 2.0.2` and `master` of this parser.

**Comment by nzakas** [comment]
We don't support TypeScript 2 yet, so the errors are expected. Try installing TypeScript 1.8 instead.

For the AST, `modifiers` in the TS AST tend to refer to all kinds of things, things that ESTree tends to put directly on a node. For instance `async` ends up in the `modifiers` array, but in ESTree, `async` is a property on the node.

So the `visibility` approach I mentioned in more in format that ESTree tends to present things.

**Comment by dannyfritz** [comment]
:+1: Thanks for the guidance.

**Comment by JamesHenry** [comment]
Just FYI, the TypeScript spec refers to this in terms of "accessibility", rather than "visibility":

https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#822-accessibility
