### ISSUE TITLE
Smoke testing against popular projects

### ISSUE THREAD

**Issue by corbinu** [eslint/typescript-eslint-parser#95]
This started when I tested the parser against VSCode and found this issue: https://github.com/eslint/typescript-eslint-parser/issues/92

The test repo can be found here: https://github.com/corbinu/eslint-typescript-smoketest

I setup a set of smoke tests that run against a few popular and large TypeScript projects. I set them up on Gitlab CI since that is what I am most familiar with. I am happy to just keep testing and reporting issues. Or if you guys want to try to integrate them into your bot and CI framework I will help however I can. 

I will say that I am thinking they should be broken up as actually two tests for each set of files one that just parses (which after issues #92 is fixed should be green on all of them based on my testing). Then a second smoke test which should have a .eslintrc.json which matches each projects current TSLint config. These would all be failing for now but eventually should turn Green as the rules get fixed.

**Comment by nzakas** [comment]
In the short term, I think it may be best to have you keep running it and report issues. We're still in the experimental phase where we are trying to figure out the best AST structure to use for various things, so it's likely smoke tests will break frequently  

Once we hit 1.0.0 and believe the project is stable, then I think it makes sense to have one or more smoke tests we manage to look for regressions. 

Thoughts?

**Comment by corbinu** [comment]
Sounds good to me that will give me some time to mature then and then maybe somebody can help me convert them over to Jenkins

**Comment by JamesHenry** [comment]
Seems like we are in agreement, thanks a lot @corbinu!

I'll close this issue for now as it has no action items, please feel free to keep reporting any issues that arise from your tests.
